#!/usr/bin/env python3
"""Generate src/data/tool-dates.ts for the landing page's Recently added /
updated lists. Runs automatically before every build (see the `prebuild` npm
script + .npmrc), so the lists refresh themselves — no manual date entry.

Per tool:
  added   — stable creation date. Reused from the previously generated file
            (a committed seed); for a brand-new tool, taken from the origin
            GitHub repo's created_at, else the file's first git commit.
  updated — the date the vendored file was last changed **in git** (advances
            automatically every time you edit a tool and commit), floored by any
            previously stored value / UPDATED_OVERRIDES so it never regresses and
            still works on shallow CI clones where git history is thin.

`gh` is only called for tools missing from the seed (normally none), so ordinary
builds need just `git` + `python3`. Everything degrades gracefully if a source
is unavailable.
"""

import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOOLS_TS = ROOT / "src" / "data" / "tools.ts"
OUT = ROOT / "src" / "data" / "tool-dates.ts"

# slug -> source repo name, when it differs from the slug
REPO_OVERRIDES = {"blog-to-substack": "blog-rss-to-substack"}

# Floor dates for tools edited in-catalog before that edit was committed to git.
# Once the edit is committed, git supersedes these automatically.
UPDATED_OVERRIDES = {
    "typing-test": "2026-07-30",          # 5-level rewrite + custom text
    "odia-numerals-clock": "2026-07-30",  # corrected number spellings
    "sip-calculator": "2026-07-30",       # growth chart + input alignment
}


def slugs() -> list[str]:
    return re.findall(r'^\s*t\(\s*"([^"]+)"', TOOLS_TS.read_text(), re.M)


def prev_dates() -> dict[str, dict[str, str]]:
    """Parse the previously generated file: slug -> {added, updated}."""
    if not OUT.exists():
        return {}
    pat = re.compile(
        r'"([^"]+)":\s*\{\s*added:\s*"([^"]*)",\s*updated:\s*"([^"]*)"\s*\}'
    )
    return {
        m.group(1): {"added": m.group(2), "updated": m.group(3)}
        for m in pat.finditer(OUT.read_text())
    }


def gh_dates(repo: str) -> tuple[str, str] | None:
    try:
        out = subprocess.run(
            ["gh", "api", f"repos/soumendrak/{repo}",
             "--jq", "[.created_at, .pushed_at] | @tsv"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        created, pushed = out.split("\t")
        return created[:10], pushed[:10]
    except (subprocess.CalledProcessError, ValueError, FileNotFoundError):
        return None


def git_dates(rel: str) -> tuple[str | None, str | None]:
    """(first_commit_date, last_commit_date) for a path, following renames."""
    try:
        out = subprocess.run(
            ["git", "-C", str(ROOT), "log", "--follow", "--format=%cs", "--", rel],
            capture_output=True, text=True, check=True,
        ).stdout.split()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None, None
    dates = [d for d in out if d]
    return (dates[-1], dates[0]) if dates else (None, None)


def main() -> None:
    prev = prev_dates()
    data: dict[str, dict[str, str]] = {}
    for slug in slugs():
        rel = f"public/tools/{slug}/index.html"
        first, last = git_dates(rel)
        gh = None

        added = prev.get(slug, {}).get("added") or first
        if not added:
            gh = gh_dates(REPO_OVERRIDES.get(slug, slug))
            added = gh[0] if gh else None
        if not added:
            print(f"  ! no added date for {slug} — skipping")
            continue

        # updated = latest of: git last commit, prior value, manual floor, gh push.
        candidates = [
            d for d in (last, prev.get(slug, {}).get("updated"),
                        UPDATED_OVERRIDES.get(slug)) if d
        ]
        if not candidates:
            if gh is None:
                gh = gh_dates(REPO_OVERRIDES.get(slug, slug))
            candidates = [gh[1] if gh else added]
        data[slug] = {"added": added, "updated": max(candidates)}

    body = ",\n".join(
        f'  "{s}": {{ added: "{d["added"]}", updated: "{d["updated"]}" }}'
        for s, d in data.items()
    )
    OUT.write_text(
        "// Generated by scripts/tool-dates.py — do not edit by hand.\n"
        "// Refreshed automatically before every build (prebuild).\n"
        "export const TOOL_DATES: Record<string, { added: string; updated: string }> = {\n"
        f"{body},\n}};\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(data)} tools)")


if __name__ == "__main__":
    main()
